### ISSUE TITLE
error on run appsody deploy

### ISSUE THREAD

**Issue by jaricsng** [kabanero-io/guide-collection-springboot2#4]
with reference to the tutorial for [springbboo2](https://kabanero.io/guides/collection-springboot2/#deploying-to-kubernetes) encountered the following error on executing ```appsody deploy``` to kuberentes.

using Docker desktop kubernetes

```
[Docker] Step 15/24 : RUN yum upgrade --disableplugin=subscription-manager -y    && yum clean --disableplugin=subscription-manager packages
[Docker]  ---> Running in 8a458ef628cd
[Docker] Red Hat Universal Base Image 8 (RPMs) - AppStre 0.0  B/s |   0  B     00:32
[Docker] Error: Failed to synchronize cache for repo 'ubi-8-appstream'
[Docker] The command '/bin/sh -c yum upgrade --disableplugin=subscription-manager -y    && yum clean --disableplugin=subscription-manager packages' returned a non-zero code: 1
[Error] exit status 1
```

**Comment by kilnerm** [comment]
This looks like it should be a transient error and seems to be an issue with the base OS features rather than something specific to the collection.

I would expect that repeating the deploy at a later point in time should result in success.

This issue will not occur when using release 0.2 of collections as the Docker images have been updated and no longer run the yum installation on the deploy step.

**Comment by SueChaplain** [comment]
@jaricsng - thanks for reporting your issue. Based on @kilnerm response, it sounds as if an upgrade to 0.2 might be your best option to avoid this issue, if re-running the deploy did not fix the problem.

Matt, the guide currently covers instructions for the v 0.1.2 release. Should these be updated to 0.2 incase there is some adverse behaviour with `yum`? If so I'll update and create a PR for you to review.

**Comment by kilnerm** [comment]
@SueChaplain I think the behavior exhibited here would be an exception rather than the rule. Have we got somewhere we can put this outside the guide, like a Q&A section for the 0.1.2 release?

**Comment by SueChaplain** [comment]
If there is a release README file for 0.1.2 I would recommend updating that.

**Comment by kilnerm** [comment]
@SueChaplain @Charlotte-Holt Can we update the guide to point at the latest kabanero index in the getting started section...

```
https://github.com/kabanero-io/collections/releases/download/0.2.1/kabanero-index.yaml
```

**Comment by SueChaplain** [comment]
@kilnerm - please review PR https://github.com/kabanero-io/guide-collection-springboot2/pull/5

**Comment by SueChaplain** [comment]
Issue fixed in https://github.com/kabanero-io/guide-collection-springboot2/pull/6 by updating the versions to 0.2.1.
